services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: go
    container_name: fexec
    volumes:
      - type: bind
        source: ../
        target: /go/src
      - type: bind
        source: ~/.aws
        target: /root/.aws
    working_dir: /go/src
    environment:
      - TZ=Asia/Tokyo
    tty: true
